### PR TITLE
Standard format for argument docstrings

### PR DESCRIPTION
**Pull request by 96RadhikaJadhav**
This PR will resolve issue #97 .

### CODE REVIEW

**Comment by ysimonson** [comment]
Thanks for this! Could you remove the space between the closing backtick and the `:`? That way it'll be in-line with the other docs.

**Comment by 96RadhikaJadhav** [comment]
> Thanks for this! Could you remove the space between the closing backtick and the `:`? That way it'll be in-line with the other docs.

@ysimonson  Done :) .

**Comment by ysimonson** [comment]
It looks like there's still entries with the old format. Running ```ag '` -'``` from master yields:

```
lib/src/sledds/datastore.rs
29:    /// * `factor` - The zstd compression factor to use. If unspecified, this
60:    /// * `path` - The file path to the Sled database.
61:    /// * `opts` - Sled options to pass in.
95:    /// * `path` - The file path to the Sled database.

lib/src/lib.rs
1://! `IndraDB` - a graph datastore.

lib/src/util.rs
59:/// * `uuid` - The input UUID.

lib/src/models/edges.rs
24:    /// * `outbound_id` - The id of the outbound vertex.
25:    /// * `t` - The type of the edge.
26:    /// * `inbound_id` - The id of the inbound vertex.
60:    /// * `key` - The key to the edge.
68:    /// * `key` - The key to the edge.
69:    /// * `created_datetime` - When the edge was created.

lib/src/models/properties.rs
21:    /// * `id` - The id of the vertex.
22:    /// * `value` - The property value.
43:    /// * `id` - The id of the vertex.
44:    /// * `value` - The property value.
63:    /// * `vertex` - The vertex information
64:    /// * `props` - The properties
83:    /// * `edge` - The edge information
84:    /// * `props` - The properties
105:    /// * `key` - The key to the edge.
106:    /// * `value` - The property value.

lib/src/rdb/datastore.rs
227:    /// * `path` - The file path to the rocksdb database.
228:    /// * `max_open_files` - The maximum number of open files to have. If
252:    /// * `path` - The file path to the rocksdb database.
253:    /// * `max_open_files` - The maximum number of open files to have. If

lib/src/models/types.rs
22:    /// * `t` - The type, which must be less than 256 characters long.
43:    /// * `t` - The type, which must be less than 256 characters long.

lib/src/models/queries.rs
92:    /// * `name` - The name of the property to get.
132:    /// * `limit` - Limits the number of returned results.
144:    /// * `t` - Sets the type filter.
156:    /// * `start_id` - The lowest vertex ID to return.
180:    /// * `ids` - The IDs of the vertices to get.
188:    /// * `id` - The ID of the vertex to get.
219:    /// * `inner` - The edge query to build off of.
220:    /// * `direction` - Whether to get outbound or inbound vertices on the
234:    /// * `limit` - Limits the number of returned results.
247:    /// * `t` - Sets the type filter.
272:    /// * `inner` - The vertex query to build off of.
273:    /// * `name` - The name of the property to get.
320:    /// * `name` - The name of the property to get.
340:    /// * `keys` - The keys of the edges to get.
348:    /// * `key` - The key of the edge to get.
385:    /// * `inner` - The edge query to build off of.
386:    /// * `direction` - Whether to get outbound or inbound edges on the
388:    /// * `limit` - Limits the number of edges to get.
403:    /// * `limit` - Limits the number of returned results.
418:    /// * `t` - Sets the type filter.
433:    /// * `high` - The newest update datetime for the edges returned.
448:    /// * `low` - The oldest update datetime for the edges returned.
475:    /// * `inner` - The edge query to build off of.
476:    /// * `name` - The name of the property to get.

lib/src/models/vertices.rs
27:    /// * `t` - The type of the vertex.
36:    /// * `id` - The id of the vertex.
37:    /// * `t` - The type of the vertex.

lib/src/bytes.rs
78:/// * `datetime` - The datetime to convert.

lib/src/traits.rs
97:    /// * `q` - The query to run.
103:    /// * `q` - The query to run.
121:    /// * `q` - The query to run.
127:    /// * `q` - The query to run.
133:    /// * `id` - The id of the vertex.
134:    /// * `t` - Only get the count for a specified edge type.
141:    /// * `q` - The query to run.
142:    /// * `name` - The property name.
148:    /// * `q` - The query to run.
154:    /// * `q` - The query to run.
155:    /// * `name` - The property name.
156:    /// * `value` - The property value.
162:    /// * `q` - The query to run.
163:    /// * `name` - The property name.
169:    /// * `q` - The query to run.
170:    /// * `name` - The property name.
176:    /// * `q` - The query to run.
182:    /// * `q` - The query to run.
183:    /// * `name` - The property name.
184:    /// * `value` - The property value.
190:    /// * `q` - The query to run.
191:    /// * `name` - The property name.
```

**Comment by 96RadhikaJadhav** [comment]
@ysimonson I have done the requested changes and squashed all the commits into one. Please review it and let me know if anything else needs to be done here.

**Pull request merged**
