### PR TITLE
#143 Use value_t macro to parse CLI args

### LINKED ISSUE #143: Use value_t! macro on CLI arg parsing
We could use [clap's value_t! macro](https://docs.rs/clap/2.33.0/clap/macro.value_t.html) to simplify parsing the integer arguments in `cli.rs`.

### PR DESCRIPTION
**Pull request by binoychitale**
Signed-off-by: binoychitale <binoychitale@gmail.com>

Fixes #143

### CODE REVIEW

**Comment by binoychitale** [comment]
These seem to be some clippy error which is causing the CI pipeline to fail.
On first look it seems unrelated to the changes in this PR

**Comment by ysimonson** [comment]
This looks good! Yeah, clippy updates its checks from time to time. I'll go ahead and address the clippy issues now.

**Comment by ysimonson** [comment]
Fixes on master

**Comment by binoychitale** [comment]
rebased onto master

**Comment by ysimonson** [comment]
Thanks for this!

**Pull request merged**
