### PR TITLE
fix incorrect `lower_bound` for inbound pipe

### LINKED ISSUE #280: Unable to get edges with `SpecificVertexQuery.inbound`
I wrote a mini program for reproduction:

```rust
        // Create an in-memory datastore
        let db: indradb::Database<indradb::RocksdbDatastore> = indradb::RocksdbDatastore::new_db("tmpdb").unwrap();

        // Create a couple of vertices
        let out_v = indradb::Vertex::new(indradb::Identifier::new("person").unwrap());
        let in_v = indradb::Vertex::new(indradb::Identifier::new("movie").unwrap());
        db.create_vertex(&out_v).unwrap();
        db.create_vertex(&in_v).unwrap();

        // Add an edge between the vertices
        let edge = indradb::Edge::new(out_v.id, indradb::Identifier::new("likes").unwrap(), in_v.id);
        db.create_edge(&edge).unwrap();

        // Query for the edge, by outbound of the out_v
        let output = db.get(indradb::SpecificVertexQuery::new(vec![out_v.id]).outbound().unwrap()).unwrap();
        // Convenience function to extract out the edges from the query results
        let e = indradb::util::extract_edges(output).unwrap();
        println!("{:?}", e);
        assert_eq!(e.len(), 1);
        assert_eq!(edge, e[0]);
        // all works fine

        // Query for the edge, by inbound of the in_v
        let output_failed = db.get(indradb::SpecificVertexQuery::new(vec![in_v.id]).inbound().unwrap()).unwrap();
        // Convenience function to extract out the edges from the query results
        let e_failed = indradb::util::extract_edges(output_failed).unwrap();
        println!("{:?}", e_failed);
        assert_eq!(e_failed.len(), 1); // panic here
        assert_eq!(edge, e_failed[0]);
```

Error:
```
running 1 test
[Edge { outbound_id: 6375f969-ad62-11ed-8000-000000000000, t: Identifier(0x7f36ac0177a0 : "likes"), inbound_id: 6375f987-ad62-11ed-8001-000000000000 }]
[]
thread 'tests::test_inbound' panicked at 'assertion failed: `(left == right)`
  left: `0`,
 right: `1`', src/main.rs:126:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/core/src/panicking.rs:64:14
   2: core::panicking::assert_failed_inner
   3: core::panicking::assert_failed
             at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/core/src/panicking.rs:199:5
   4: test_indradb::tests::test_inbound
             at ./src/main.rs:126:9
   5: test_indradb::tests::test_inbound::{{closure}}
             at ./src/main.rs:99:23
   6: core::ops::function::FnOnce::call_once
             at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/core/src/ops/function.rs:507:5
   7: core::ops::function::FnOnce::call_once
             at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/core/src/ops/function.rs:507:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
test tests::test_inbound ... FAILED
```

Apparently, the `inbound()` of `in_v` should have contained the `edge`, as what `outbound()` of `out_v` returns.

### PR DESCRIPTION
**Pull request by C0MM4ND**
close #280

### CODE REVIEW

**Comment by ysimonson** [comment]
Would you mind adding a test for the mini program reproduction? That way we can prevent this regression from happening again. This PR should give an idea of how to do it: https://github.com/indradb/indradb/pull/279/files

**Comment by C0MM4ND** [comment]
This test cannot detect #280, cuz I dont know how to make the db dirty before the testing. Current test is running on tempdir, it seems always clean.

**Comment by ysimonson** [comment]
Hm, something here doesn't seem right. Could you clarify what you mean by dirty? If it's just re-opening the database, we can reproduce that in a test:

```rust
#[test]
pub fn should_get_correct_inbounds_and_outbounds_edges() {
    use crate::QueryExt;
    use super::RocksdbDatastore;
    use tempfile::tempdir;

    let dir = tempdir().unwrap();

    let (out_v, edge, in_v) = {
        let db = RocksdbDatastore::new_db_with_options(dir.path(), &RocksdbDatastore::get_options(Some(1))).unwrap();

        // Create a couple of vertices
        let out_v = crate::Vertex::new(crate::Identifier::new("person").unwrap());
        let in_v = crate::Vertex::new(crate::Identifier::new("movie").unwrap());
        db.create_vertex(&out_v).unwrap();
        db.create_vertex(&in_v).unwrap();

        // Add an edge between the vertices
        let edge = crate::Edge::new(out_v.id, crate::Identifier::new("likes").unwrap(), in_v.id);
        db.create_edge(&edge).unwrap();

        (out_v, edge, in_v)
    };

    {
        let db = RocksdbDatastore::new_db_with_options(dir.path(), &RocksdbDatastore::get_options(Some(1))).unwrap();
        // Query for the edge, by outbound of the out_v
        let output = db
            .get(crate::SpecificVertexQuery::new(vec![out_v.id]).outbound().unwrap())
            .unwrap();

        let e = crate::util::extract_edges(output).unwrap();
        assert_eq!(e.len(), 1);
        assert_eq!(edge, e[0]);
        assert_eq!(edge.inbound_id, in_v.id);
        assert_eq!(edge.outbound_id, out_v.id);
        // all works fine

        // Query for the edge, by inbound of the in_v
        let output_failed = db
            .get(crate::SpecificVertexQuery::new(vec![in_v.id]).inbound().unwrap())
            .unwrap();

        let e_failed = crate::util::extract_edges(output_failed).unwrap();
        assert_eq!(e_failed.len(), 1);
        assert_eq!(edge, e_failed[0]);
        assert_eq!(edge.inbound_id, in_v.id);
        assert_eq!(edge.outbound_id, out_v.id);
    }
}
```

Though this doesn't seem to fail without the fix applied.

**Comment by C0MM4ND** [comment]
My local test is written on the bottom of the `./lib/src/database.rs`

```rust

#[cfg(test)]
mod tests {
    use crate::QueryExt;

    // Note this useful idiom: importing names from outer (for mod tests) scope.
    use super::*;
    use tempfile::tempdir;

    #[test]
    fn test() {
        let path = tempdir().unwrap().into_path();

        {
            // Create an in-memory datastore
            let db: crate::Database<crate::RocksdbDatastore> = crate::RocksdbDatastore::new_db(&path).unwrap();

            // Create a couple of vertices
            let out_v = crate::Vertex::new(crate::Identifier::new("person").unwrap());
            let in_v = crate::Vertex::new(crate::Identifier::new("movie").unwrap());
            db.create_vertex(&out_v).unwrap();
            db.create_vertex(&in_v).unwrap();

            // Add an edge between the vertices
            let edge = crate::Edge::new(out_v.id, crate::Identifier::new("likes").unwrap(), in_v.id);
            db.create_edge(&edge).unwrap();

            // Query for the edge, by outbound of the out_v
            let output = db
                .get(crate::SpecificVertexQuery::new(vec![out_v.id]).outbound().unwrap())
                .unwrap();

            let e = crate::util::extract_edges(output).unwrap();
            assert_eq!(e.len(), 1);
            assert_eq!(edge, e[0]);
            assert_eq!(edge.inbound_id, in_v.id);
            assert_eq!(edge.outbound_id, out_v.id);
            // all works fine

            // Query for the edge, by inbound of the in_v
            let output_failed = db
                .get(crate::SpecificVertexQuery::new(vec![in_v.id]).inbound().unwrap())
                .unwrap();

            let e_failed = crate::util::extract_edges(output_failed).unwrap();
            assert_eq!(e_failed.len(), 1);
            assert_eq!(edge, e_failed[0]);
            assert_eq!(edge.inbound_id, in_v.id);
            assert_eq!(edge.outbound_id, out_v.id);
        }

        {
            // Create an in-memory datastore
            let db: crate::Database<crate::RocksdbDatastore> = crate::RocksdbDatastore::new_db(&path).unwrap();

            // Create a couple of vertices
            let out_v = crate::Vertex::new(crate::Identifier::new("person").unwrap());
            let in_v = crate::Vertex::new(crate::Identifier::new("movie").unwrap());
            db.create_vertex(&out_v).unwrap();
            db.create_vertex(&in_v).unwrap();

            // Add an edge between the vertices
            let edge = crate::Edge::new(out_v.id, crate::Identifier::new("likes").unwrap(), in_v.id);
            db.create_edge(&edge).unwrap();

            // Query for the edge, by outbound of the out_v
            let output = db
                .get(crate::SpecificVertexQuery::new(vec![out_v.id]).outbound().unwrap())
                .unwrap();

            let e = crate::util::extract_edges(output).unwrap();
            assert_eq!(e.len(), 1);
            assert_eq!(edge, e[0]);
            assert_eq!(edge.inbound_id, in_v.id);
            assert_eq!(edge.outbound_id, out_v.id);
            // all works fine

            // Query for the edge, by inbound of the in_v
            let output_failed = db
                .get(crate::SpecificVertexQuery::new(vec![in_v.id]).inbound().unwrap())
                .unwrap();

            let e_failed = crate::util::extract_edges(output_failed).unwrap();
            assert_eq!(e_failed.len(), 1); // <- panic here, line 782
            assert_eq!(edge, e_failed[0]);
            assert_eq!(edge.inbound_id, in_v.id);
            assert_eq!(edge.outbound_id, out_v.id);
        }
    }
}

```

this will **always panic** when `lower_bound` doesnt get `reverse()`.

```
running 1 test
thread 'database::tests::test' panicked at 'assertion failed: `(left == right)`
  left: `0`,
 right: `1`', lib/src/database.rs:782:13
stack backtrace:
   0: rust_begin_unwind
             at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/core/src/panicking.rs:64:14
   2: core::panicking::assert_failed_inner
   3: core::panicking::assert_failed
             at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/core/src/panicking.rs:199:5
   4: indradb::database::tests::test
             at ./src/database.rs:782:13
   5: indradb::database::tests::test::{{closure}}
             at ./src/database.rs:709:15
   6: core::ops::function::FnOnce::call_once
             at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/core/src/ops/function.rs:507:5
   7: core::ops::function::FnOnce::call_once
             at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/core/src/ops/function.rs:507:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
test database::tests::test ... FAILED

failures:

failures:
    database::tests::test
```

**Comment by ysimonson** [comment]
Nice. To simplify it:

```rust
   #[test]
    fn test_repeated_reverse_fetch_operation() {
        let path = tempdir().unwrap().into_path();

        for _i in 0..2 {
            // Create an in-memory datastore
            let db: crate::Database<crate::RocksdbDatastore> = crate::RocksdbDatastore::new_db(&path).unwrap();

            // Create a couple of vertices
            let out_v = crate::Vertex::new(crate::Identifier::new("person").unwrap());
            let in_v = crate::Vertex::new(crate::Identifier::new("movie").unwrap());
            db.create_vertex(&out_v).unwrap();
            db.create_vertex(&in_v).unwrap();

            // Add an edge between the vertices
            let edge = crate::Edge::new(out_v.id, crate::Identifier::new("likes").unwrap(), in_v.id);
            db.create_edge(&edge).unwrap();

            // Query for the edge, by outbound of the out_v
            let output = db
                .get(crate::SpecificVertexQuery::new(vec![out_v.id]).outbound().unwrap())
                .unwrap();

            let e = crate::util::extract_edges(output).unwrap();
            assert_eq!(e.len(), 1);
            assert_eq!(edge, e[0]);
            assert_eq!(edge.inbound_id, in_v.id);
            assert_eq!(edge.outbound_id, out_v.id);
            // all works fine

            // Query for the edge, by inbound of the in_v
            let output_failed = db
                .get(crate::SpecificVertexQuery::new(vec![in_v.id]).inbound().unwrap())
                .unwrap();

            let e_failed = crate::util::extract_edges(output_failed).unwrap();
            assert_eq!(e_failed.len(), 1);
            assert_eq!(edge, e_failed[0]);
            assert_eq!(edge.inbound_id, in_v.id);
            assert_eq!(edge.outbound_id, out_v.id);
        }
    }
```

**Comment by ysimonson** [comment]
closing this out in favor of #283

**Pull request closed without merging**
