### PR TITLE
Update tonic + tonic-build proto dependencies to 0.9.2

### PR DESCRIPTION
**Pull request by dmyyy**
Ran bench and tests with no issues. 

Should fix https://github.com/indradb/indradb/issues/303

TODO: New release on crates io?

### CODE REVIEW

**Comment by ysimonson** [comment]
Looks like this is causing a build failure in Ubuntu + rust nightly

**Comment by dmyyy** [comment]
> Looks like this is causing a build failure in Ubuntu + rust nightly

Same issue in a different upstream dependency

```
Compiling libc v0.2.131
[807](https://github.com/indradb/indradb/actions/runs/5512562351/jobs/10050381782?pr=304#step:5:808)
   Compiling proc-macro2 v1.0.49
[808](https://github.com/indradb/indradb/actions/runs/5512562351/jobs/10050381782?pr=304#step:5:809)
   Compiling unicode-ident v1.0.3
[809](https://github.com/indradb/indradb/actions/runs/5512562351/jobs/10050381782?pr=304#step:5:810)
error[E0635]: unknown feature `proc_macro_span_shrink`
[810](https://github.com/indradb/indradb/actions/runs/5512562351/jobs/10050381782?pr=304#step:5:811)
Error:   --> /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/proc-macro2-1.0.49/src/lib.rs:92:30
[811](https://github.com/indradb/indradb/actions/runs/5512562351/jobs/10050381782?pr=304#step:5:812)
   |
[812](https://github.com/indradb/indradb/actions/runs/5512562351/jobs/10050381782?pr=304#step:5:813)
92 |     feature(proc_macro_span, proc_macro_span_shrink)
[813](https://github.com/indradb/indradb/actions/runs/5512562351/jobs/10050381782?pr=304#step:5:814)
   |                              ^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by dmyyy** [comment]
Checked through dependencies that include proc-macro2 - seems like it should be one of tokio/axum which doesn't seem like it should be ubuntu specific. Hard to tell which specific dependency it is from the logs.

**Comment by dmyyy** [comment]
Issue seems to have been fixed upstream without any changes required here - tested on 1.70 and 1.71/1.73 nightly

**Pull request closed without merging**
